#include "HelloJNIImpl.h"
#include <iostream>
#include <jni.h>
#include "HelloJNI.h"   // auto-generated by `javah HelloJNI`

/*
 * Class:	HelloJNI
 * Method:	sayHello
 * Signature: 	(Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello (JNIEnv *env, jobject thisObj, jstring arg) {
	const char *sarg = env->GetStringUTFChars(arg, 0);
	std::cerr << "Hello, " << sarg << "!" << std::endl;
	env->ReleaseStringUTFChars(arg, sarg);
}
