version: '3.3'
services:
    adminbackend:
        image: jazzdd/alpine-flask:python3
        container_name: adminbackend
        ports:
            - 8000:80
        volumes:
            - .:/app/
        working_dir: /app/
