/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 22:07:16 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"app.cob"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "app.c.h"

/* Function prototypes */

int CLIENTES (void);
static int CLIENTES_ (const int);

/* Functions */

int
CLIENTES ()
{
  return CLIENTES_ (0);
}

static int
CLIENTES_ (const int entry)
{
  /* Local variables */
  #include "app.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, &f_144, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	cob_close (h_FILE1, 0, NULL);
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      if (module.next)
        cob_set_cancel ((const char *)"CLIENTES", (void *)CLIENTES, (void *)CLIENTES_);
      (*(int *) (b_1)) = 0;
      memcpy (b_12, "CLIENTES - ", 11);
      memset (b_12 + 11, 32, 20);
      *(unsigned char *)(b_15) = 32;
      memset (b_21, 48, 2);
      *(unsigned char *)(b_25) = 32;
      memset (b_27, 48, 3);
      memset (b_28, 48, 3);
      *(b_29) = 48;
      *(b_30) = 50;
      memset (b_31, 32, 30);
      memset (b_32, 32, 80);
      memset (b_144, 48, 4);

      if (!h_FILE1)
      {
        h_FILE1 = cob_malloc (sizeof(cob_file));
      }
      if (!k_FILE1)
      {
        k_FILE1 = cob_malloc (sizeof (struct cob_file_key) * 1);
      }
      k_FILE1->field = &f_6;
      k_FILE1->flag = 0;
      k_FILE1->offset = 0;
      h_FILE1->select_name = (const char *)"FILE1";
      h_FILE1->file_status = h_FILE1_status;
      memset (h_FILE1_status, '0', 2);
      h_FILE1->assign = &c_22;
      h_FILE1->record = &f_11;
      h_FILE1->record_size = NULL;
      h_FILE1->record_min = 109;
      h_FILE1->record_max = 109;
      h_FILE1->nkeys = 1;
      h_FILE1->keys = k_FILE1;
      h_FILE1->file = NULL;
      h_FILE1->organization = 3;
      h_FILE1->access_mode = 3;
      h_FILE1->lock_mode = 0;
      h_FILE1->open_mode = 0;
      h_FILE1->flag_optional = 0;
      h_FILE1->last_open_mode = 0;
      h_FILE1->special = 0;
      h_FILE1->flag_nonexistent = 0;
      h_FILE1->flag_end_of_file = 0;
      h_FILE1->flag_begin_of_file = 0;
      h_FILE1->flag_first_read = 0;
      h_FILE1->flag_read_done = 0;
      h_FILE1->flag_select_features = 1;
      h_FILE1->flag_needs_nl = 0;
      h_FILE1->flag_needs_top = 0;
      h_FILE1->file_version = 0;

      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry CLIENTES */

  l_2:;

  /* MAIN SECTION */

  /* INICIO */

  /* app.cob:98: SET */
  {
    cob_set_environment (&c_23, &c_24);
  }
  /* app.cob:99: SET */
  {
    cob_set_environment (&c_25, &c_24);
  }
  /* app.cob:100: SET */
  {
    cob_set_environment (&c_26, &c_27);
  }
  /* app.cob:101: ACCEPT */
  {
    cob_screen_line_col (&f_27, 0);
  }
  /* app.cob:102: ACCEPT */
  {
    cob_screen_line_col (&f_28, 1);
  }
  /* app.cob:103: PERFORM */
  {
    /* PERFORM ABRIR-ARQUIVOS */
    frame_ptr++;
    frame_ptr->perform_through = 19;
    frame_ptr->return_address = &&l_21;
    goto l_19;
    l_21:
    frame_ptr--;
  }
  /* app.cob:104: PERFORM */
  {
    while (1)
      {
        if ((((int)(int)(*(b_15) - 113) == 0) || ((int)(int)(*(b_15) - 120) == 0)))
          break;
        {
          /* app.cob:105: MOVE */
          {
            cob_move (&c_28, &f_14);
          }
          /* app.cob:106: MOVE */
          {
            memcpy (b_31, "\105\123\103\117\114\110\101\040\101\040\117\120\303\207\303\203\117\040\040\040\040\040\040\040\040\040\040\040\040\040", 30);
          }
          /* app.cob:107: MOVE */
          {
            *(b_15) = 32;
          }
          /* app.cob:108: DISPLAY */
          {
            cob_move (&f_31, &f_122);
            cob_move (&f_12, &f_120);
            cob_screen_display (&s_114, NULL, NULL);
          }
          /* app.cob:109: ACCEPT */
          {
            cob_move (&f_15, &f_130);
            cob_screen_accept (&s_123, NULL, NULL);
            cob_move (&f_130, &f_15);
          }
          /* app.cob:110: EVALUATE */
          {
            if (((int)(int)(*(b_15) - 49) == 0))
              {
                /* app.cob:112: PERFORM */
                {
                  /* PERFORM ADDITION THRU ADDITION-FIM */
                  frame_ptr++;
                  frame_ptr->perform_through = 8;
                  frame_ptr->return_address = &&l_22;
                  goto l_6;
                  l_22:
                  frame_ptr--;
                }
              }
            else
              if (((int)(int)(*(b_15) - 50) == 0))
                {
                  /* app.cob:114: PERFORM */
                  {
                    /* PERFORM CONSULTA THRU CONSULTA-FIM */
                    frame_ptr++;
                    frame_ptr->perform_through = 11;
                    frame_ptr->return_address = &&l_23;
                    goto l_9;
                    l_23:
                    frame_ptr--;
                  }
                }
              else
                if (((int)(int)(*(b_15) - 51) == 0))
                  {
                    /* app.cob:116: PERFORM */
                    {
                      /* PERFORM ALTERA THRU ALTERA-FIM */
                      frame_ptr++;
                      frame_ptr->perform_through = 14;
                      frame_ptr->return_address = &&l_24;
                      goto l_12;
                      l_24:
                      frame_ptr--;
                    }
                  }
                else
                  if (((int)(int)(*(b_15) - 52) == 0))
                    {
                      /* app.cob:118: PERFORM */
                      {
                        /* PERFORM EXCLUI THRU EXCLUI-FIM */
                        frame_ptr++;
                        frame_ptr->perform_through = 16;
                        frame_ptr->return_address = &&l_25;
                        goto l_15;
                        l_25:
                        frame_ptr--;
                      }
                    }
          }
        }
      }
  }

  /* FINALIZA */

  /* app.cob:122: CLOSE */
  {
    cob_exception_code = 0;
    {
      cob_close (h_FILE1, 0, &f_21);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_26;
        goto l_1;
        l_26:
        frame_ptr--;
      }
  }
  /* app.cob:123: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* ADDITION */

  l_6:;
  /* app.cob:127: MOVE */
  {
    memcpy (b_12 + 11, "\111\116\103\114\125\123\303\203\117\040\040\040\040\040\040\040\040\040\040\040", 20);
  }
  /* app.cob:128: MOVE */
  {
    memcpy (b_31, "ESC PARA ENCERRAR             ", 30);
  }
  /* app.cob:129: DISPLAY */
  {
    cob_move (&f_31, &f_122);
    cob_move (&f_12, &f_120);
    cob_screen_display (&s_114, NULL, NULL);
  }
  /* app.cob:130: MOVE */
  {
    memset (b_11, 32, 109);
  }

  /* ADDITION-LOOP */

  l_7:;
  /* app.cob:132: ACCEPT */
  {
    cob_move (&f_9, &f_139);
    cob_move (&f_8, &f_137);
    cob_move (&f_7, &f_134);
    cob_screen_accept (&s_131, NULL, NULL);
    cob_move (&f_139, &f_9);
    cob_move (&f_137, &f_8);
    cob_move (&f_134, &f_7);
  }
  /* app.cob:133: IF */
  {
    if (((int)cob_cmp_numdisp (b_144, 4, 2005) == 0))
      {
        /* app.cob:134: GO TO */
        {
          goto l_8;
        }
      }
  }
  /* app.cob:136: IF */
  {
    if ((((int)cob_cmp (&f_8, &cob_space) == 0) || ((int)cob_cmp (&f_9, &cob_space) == 0)))
      {
        /* app.cob:137: MOVE */
        {
          cob_move (&c_29, &f_32);
        }
        /* app.cob:138: PERFORM */
        {
          /* PERFORM MOSTRA-ERRO */
          frame_ptr++;
          frame_ptr->perform_through = 20;
          frame_ptr->return_address = &&l_27;
          goto l_20;
          l_27:
          frame_ptr--;
        }
        /* app.cob:139: GO TO */
        {
          goto l_7;
        }
      }
  }
  /* app.cob:141: WRITE */
  cob_exception_code = 0;
  {
    cob_write (h_FILE1, &f_5, 0, &f_21);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0506)
        {
          {
            /* app.cob:143: MOVE */
            {
              cob_move (&c_30, &f_32);
            }
            /* app.cob:144: PERFORM */
            {
              /* PERFORM MOSTRA-ERRO */
              frame_ptr++;
              frame_ptr->perform_through = 20;
              frame_ptr->return_address = &&l_28;
              goto l_20;
              l_28:
              frame_ptr--;
            }
            /* app.cob:145: MOVE */
            {
              memset (b_11, 48, 9);
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_29;
          goto l_1;
          l_29:
          frame_ptr--;
        }
    }
  /* app.cob:147: GO TO */
  {
    goto l_6;
  }

  /* ADDITION-FIM */

  l_8:;

  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address;

  /* CONSULTA */

  l_9:;
  /* app.cob:152: MOVE */
  {
    memcpy (b_12 + 11, "CONSULTA            ", 20);
  }
  /* app.cob:153: MOVE */
  {
    memcpy (b_31, "ESC PARA ENCERRAR             ", 30);
  }
  /* app.cob:154: DISPLAY */
  {
    cob_move (&f_31, &f_122);
    cob_move (&f_12, &f_120);
    cob_screen_display (&s_114, NULL, NULL);
  }

  /* CONSULTA-LOOP */

  l_10:;
  /* app.cob:156: MOVE */
  {
    memset (b_11, 32, 109);
  }
  /* app.cob:157: DISPLAY */
  {
    cob_move (&f_9, &f_139);
    cob_move (&f_8, &f_137);
    cob_move (&f_7, &f_134);
    cob_screen_display (&s_131, NULL, NULL);
  }
  /* app.cob:158: PERFORM */
  {
    /* PERFORM LE-CLIENTE THRU LE-CLIENTE-FIM */
    frame_ptr++;
    frame_ptr->perform_through = 18;
    frame_ptr->return_address = &&l_30;
    goto l_17;
    l_30:
    frame_ptr--;
  }
  /* app.cob:159: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 99) == 0))
      {
        /* app.cob:160: GO TO */
        {
          goto l_11;
        }
      }
  }
  /* app.cob:162: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 0) == 0))
      {
        /* app.cob:163: DISPLAY */
        {
          cob_move (&f_9, &f_139);
          cob_move (&f_8, &f_137);
          cob_screen_display (&s_135, NULL, NULL);
        }
        /* app.cob:164: MOVE */
        {
          cob_move (&c_31, &f_32);
        }
        /* app.cob:165: PERFORM */
        {
          /* PERFORM MOSTRA-ERRO */
          frame_ptr++;
          frame_ptr->perform_through = 20;
          frame_ptr->return_address = &&l_31;
          goto l_20;
          l_31:
          frame_ptr--;
        }
      }
  }
  /* app.cob:167: GO TO */
  {
    goto l_10;
  }

  /* CONSULTA-FIM */

  l_11:;

  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address;

  /* ALTERA */

  l_12:;
  /* app.cob:172: MOVE */
  {
    memcpy (b_12 + 11, "\101\114\124\105\122\101\303\207\303\203\117\040\040\040\040\040\040\040\040\040", 20);
  }
  /* app.cob:173: MOVE */
  {
    memcpy (b_31, "ESC PARA ENCERRAR             ", 30);
  }
  /* app.cob:174: DISPLAY */
  {
    cob_move (&f_31, &f_122);
    cob_move (&f_12, &f_120);
    cob_screen_display (&s_114, NULL, NULL);
  }

  /* ALTERA-LOOP */

  l_13:;
  /* app.cob:176: MOVE */
  {
    memset (b_11, 32, 109);
  }
  /* app.cob:177: DISPLAY */
  {
    cob_move (&f_9, &f_139);
    cob_move (&f_8, &f_137);
    cob_move (&f_7, &f_134);
    cob_screen_display (&s_131, NULL, NULL);
  }
  /* app.cob:178: PERFORM */
  {
    /* PERFORM LE-CLIENTE THRU LE-CLIENTE-FIM */
    frame_ptr++;
    frame_ptr->perform_through = 18;
    frame_ptr->return_address = &&l_32;
    goto l_17;
    l_32:
    frame_ptr--;
  }
  /* app.cob:179: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 99) == 0))
      {
        /* app.cob:180: GO TO */
        {
          goto l_14;
        }
      }
  }
  /* app.cob:182: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 0) == 0))
      {
        /* app.cob:183: ACCEPT */
        {
          cob_move (&f_9, &f_139);
          cob_move (&f_8, &f_137);
          cob_screen_accept (&s_135, NULL, NULL);
          cob_move (&f_139, &f_9);
          cob_move (&f_137, &f_8);
        }
        /* app.cob:184: IF */
        {
          if (((int)cob_cmp_numdisp (b_144, 4, 2005) == 0))
            {
              /* app.cob:185: GO TO */
              {
                goto l_13;
              }
            }
        }
      }
    else
      {
        /* app.cob:188: GO TO */
        {
          goto l_13;
        }
      }
  }
  /* app.cob:190: REWRITE */
  cob_exception_code = 0;
  {
    cob_rewrite (h_FILE1, &f_5, 0, &f_21);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0506)
        {
          {
            /* app.cob:192: MOVE */
            {
              cob_move (&c_32, &f_32);
            }
            /* app.cob:193: PERFORM */
            {
              /* PERFORM MOSTRA-ERRO */
              frame_ptr++;
              frame_ptr->perform_through = 20;
              frame_ptr->return_address = &&l_33;
              goto l_20;
              l_33:
              frame_ptr--;
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_34;
          goto l_1;
          l_34:
          frame_ptr--;
        }
    }
  else
    {
      {
        /* app.cob:195: CONTINUE */
        {
          ;
        }
      }
    }
  /* app.cob:197: GO TO */
  {
    goto l_13;
  }

  /* ALTERA-FIM */

  l_14:;

  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address;

  /* EXCLUI */

  l_15:;
  /* app.cob:202: MOVE */
  {
    memcpy (b_12 + 11, "\105\130\103\114\125\123\303\203\117\040\040\040\040\040\040\040\040\040\040\040", 20);
  }
  /* app.cob:203: MOVE */
  {
    memcpy (b_31, "ESC PARA ENCERRAR             ", 30);
  }
  /* app.cob:204: DISPLAY */
  {
    cob_move (&f_31, &f_122);
    cob_move (&f_12, &f_120);
    cob_screen_display (&s_114, NULL, NULL);
  }
  /* app.cob:205: MOVE */
  {
    memset (b_11, 32, 109);
  }
  /* app.cob:206: DISPLAY */
  {
    cob_move (&f_9, &f_139);
    cob_move (&f_8, &f_137);
    cob_move (&f_7, &f_134);
    cob_screen_display (&s_131, NULL, NULL);
  }
  /* app.cob:207: PERFORM */
  {
    /* PERFORM LE-CLIENTE THRU LE-CLIENTE-FIM */
    frame_ptr++;
    frame_ptr->perform_through = 18;
    frame_ptr->return_address = &&l_35;
    goto l_17;
    l_35:
    frame_ptr--;
  }
  /* app.cob:208: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 99) == 0))
      {
        /* app.cob:209: GO TO */
        {
          goto l_16;
        }
      }
  }
  /* app.cob:211: IF */
  {
    if (!((int)cob_cmp_numdisp (b_21, 2, 0) == 0))
      {
        /* app.cob:212: GO TO */
        {
          goto l_15;
        }
      }
  }
  /* app.cob:214: DISPLAY */
  {
    cob_move (&f_9, &f_139);
    cob_move (&f_8, &f_137);
    cob_screen_display (&s_135, NULL, NULL);
  }
  /* app.cob:215: MOVE */
  {
    *(b_25) = 78;
  }
  /* app.cob:216: MOVE */
  {
    cob_move (&c_33, &f_32);
  }
  /* app.cob:217: ACCEPT */
  {
    cob_move (&f_32, &f_142);
    cob_screen_accept (&s_140, NULL, NULL);
    cob_move (&f_143, &f_25);
  }
  /* app.cob:218: IF */
  {
    if (!(((int)(int)(*(b_25) - 83) == 0) || ((int)(int)(*(b_25) - 115) == 0)))
      {
        /* app.cob:219: GO TO */
        {
          goto l_16;
        }
      }
  }
  /* app.cob:221: DELETE */
  cob_exception_code = 0;
  {
    cob_delete (h_FILE1, &f_21);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0506)
        {
          {
            /* app.cob:223: MOVE */
            {
              cob_move (&c_34, &f_32);
            }
            /* app.cob:224: PERFORM */
            {
              /* PERFORM MOSTRA-ERRO */
              frame_ptr++;
              frame_ptr->perform_through = 20;
              frame_ptr->return_address = &&l_36;
              goto l_20;
              l_36:
              frame_ptr--;
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_37;
          goto l_1;
          l_37:
          frame_ptr--;
        }
    }

  /* EXCLUI-FIM */

  l_16:;

  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address;

  /* LE-CLIENTE */

  l_17:;
  /* app.cob:231: ACCEPT */
  {
    cob_move (&f_7, &f_134);
    cob_screen_accept (&s_132, NULL, NULL);
    cob_move (&f_134, &f_7);
  }
  /* app.cob:232: IF */
  {
    if (!((int)cob_cmp_numdisp (b_144, 4, 2005) == 0))
      {
        /* app.cob:233: READ */
        cob_exception_code = 0;
        {
          cob_read (h_FILE1, &f_6, &f_21, 0);
        }
        if (unlikely(cob_exception_code != 0))
          {
            if (cob_exception_code == 0x0506)
              {
                {
                  /* app.cob:235: MOVE */
                  {
                    cob_move (&c_35, &f_32);
                  }
                  /* app.cob:236: PERFORM */
                  {
                    /* PERFORM MOSTRA-ERRO */
                    frame_ptr++;
                    frame_ptr->perform_through = 20;
                    frame_ptr->return_address = &&l_38;
                    goto l_20;
                    l_38:
                    frame_ptr--;
                  }
                }
              }
            else
              {
                /* PERFORM Default Error Handler */
                frame_ptr++;
                frame_ptr->perform_through = 1;
                frame_ptr->return_address = &&l_39;
                goto l_1;
                l_39:
                frame_ptr--;
              }
          }
      }
    else
      {
        /* app.cob:239: MOVE */
        {
          memset (b_21, 57, 2);
        }
      }
  }

  /* LE-CLIENTE-FIM */

  l_18:;

  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address;

  /* ABRIR-ARQUIVOS */

  l_19:;
  /* app.cob:246: OPEN */
  {
    cob_exception_code = 0;
    {
      cob_open (h_FILE1, 3, 1, &f_21);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_40;
        goto l_1;
        l_40:
        frame_ptr--;
      }
  }
  /* app.cob:247: IF */
  {
    if (((int)cob_cmp_numdisp (b_21, 2, 35) == 0))
      {
        /* app.cob:248: OPEN */
        {
          cob_exception_code = 0;
          {
            cob_open (h_FILE1, 2, 1, &f_21);
          }
          if (unlikely(cob_exception_code != 0))
            {
              /* PERFORM Default Error Handler */
              frame_ptr++;
              frame_ptr->perform_through = 1;
              frame_ptr->return_address = &&l_41;
              goto l_1;
              l_41:
              frame_ptr--;
            }
        }
        /* app.cob:249: CLOSE */
        {
          cob_exception_code = 0;
          {
            cob_close (h_FILE1, 0, &f_21);
          }
          if (unlikely(cob_exception_code != 0))
            {
              /* PERFORM Default Error Handler */
              frame_ptr++;
              frame_ptr->perform_through = 1;
              frame_ptr->return_address = &&l_42;
              goto l_1;
              l_42:
              frame_ptr--;
            }
        }
        /* app.cob:250: OPEN */
        {
          cob_exception_code = 0;
          {
            cob_open (h_FILE1, 3, 1, &f_21);
          }
          if (unlikely(cob_exception_code != 0))
            {
              /* PERFORM Default Error Handler */
              frame_ptr++;
              frame_ptr->perform_through = 1;
              frame_ptr->return_address = &&l_43;
              goto l_1;
              l_43:
              frame_ptr--;
            }
        }
      }
  }

  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address;

  /* MOSTRA-ERRO */

  l_20:;
  /* app.cob:256: DISPLAY */
  {
    cob_move (&f_32, &f_142);
    cob_screen_display (&s_140, NULL, NULL);
  }
  /* app.cob:257: ACCEPT */
  {
    cob_move (&f_32, &f_142);
    cob_screen_accept (&s_140, NULL, NULL);
    cob_move (&f_143, &f_25);
  }
  /* app.cob:258: DISPLAY */
  {
    cob_move (&f_31, &f_122);
    cob_screen_display (&s_121, NULL, NULL);
  }

  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address;

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));


  /* Default Error Handler */

  l_1:;

  if (!(cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_default_error_handle ();
  	cob_stop_run (1);
  }

  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address;

  cob_fatal_error (COB_FERROR_CODEGEN);

}

/* End functions */

