/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 22:07:16 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : CLIENTES */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_11[109] __attribute__((aligned));	/* FILE1_record */
static unsigned char b_12[31] __attribute__((aligned));	/* WS-MODULO */
static unsigned char b_15[1] __attribute__((aligned));	/* WS-OPCAO */
static unsigned char b_21[2] __attribute__((aligned));	/* FS-STAT */
static unsigned char b_25[1] __attribute__((aligned));	/* WS-ERRO */
static unsigned char b_27[3] __attribute__((aligned));	/* WS-NUML */
static unsigned char b_28[3] __attribute__((aligned));	/* WS-NUMC */
static unsigned char b_29[1] __attribute__((aligned));	/* COR-FUNDO */
static unsigned char b_30[1] __attribute__((aligned));	/* COR-FRENTE */
static unsigned char b_31[30] __attribute__((aligned));	/* WS-STATUS */
static unsigned char b_32[80] __attribute__((aligned));	/* WS-MSGERRO */
static unsigned char b_114[64] __attribute__((aligned));	/* SS-CLS */
static unsigned char b_123[53] __attribute__((aligned));	/* SS-MENU */
static unsigned char b_131[113] __attribute__((aligned));	/* SS-TELA-REGISTRO */
static unsigned char b_140[81] __attribute__((aligned));	/* SS-ERRO */
static unsigned char b_144[4] __attribute__((aligned));	/* COB-CRT-STATUS */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {16, 4, 0, 0, NULL};
static const cob_field_attr a_2 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_3 = {16, 1, 0, 0, NULL};
static const cob_field_attr a_4 = {16, 3, 0, 0, NULL};
static const cob_field_attr a_5 = {16, 2, 0, 0, NULL};
static const cob_field_attr a_6 = {36, 9, 0, 8, "9\011\000\000\000"};
static const cob_field_attr a_7 = {1, 0, 0, 0, NULL};

/* Fields */

/* PROGRAM-ID : CLIENTES */
static cob_field f_5	= {109, b_11, &a_7};	/* FILE1-REC */
static cob_field f_6	= {9, b_11, &a_7};	/* FS-KEY */
static cob_field f_7	= {9, b_11, &a_6};	/* FS-FONE */
static cob_field f_8	= {40, b_11 + 9, &a_2};	/* FS-NAME */
static cob_field f_9	= {40, b_11 + 49, &a_2};	/* FS-ENDERECO */
static cob_field f_11	= {109, b_11, &a_2};	/* FILE1_record */
static cob_field f_12	= {31, b_12, &a_7};	/* WS-MODULO */
static cob_field f_14	= {20, b_12 + 11, &a_2};	/* WS-OP */
static cob_field f_15	= {1, b_15, &a_2};	/* WS-OPCAO */
static cob_field f_21	= {2, b_21, &a_5};	/* FS-STAT */
static cob_field f_25	= {1, b_25, &a_2};	/* WS-ERRO */
static cob_field f_27	= {3, b_27, &a_4};	/* WS-NUML */
static cob_field f_28	= {3, b_28, &a_4};	/* WS-NUMC */
static cob_field f_29	= {1, b_29, &a_3};	/* COR-FUNDO */
static cob_field f_30	= {1, b_30, &a_3};	/* COR-FRENTE */
static cob_field f_31	= {30, b_31, &a_2};	/* WS-STATUS */
static cob_field f_32	= {80, b_32, &a_2};	/* WS-MSGERRO */
static cob_field f_114	= {64, b_114, &a_7};	/* SS-CLS */
static cob_field f_116	= {1, b_114, &a_2};	/* WORK$3 */
static cob_field f_117	= {1, b_114 + 1, &a_2};	/* WORK$4 */
static cob_field f_118	= {1, b_114 + 2, &a_2};	/* WORK$5 */
static cob_field f_120	= {31, b_114 + 3, &a_2};	/* WORK$6 */
static cob_field f_121	= {30, b_114 + 34, &a_7};	/* SS-STATUS */
static cob_field f_122	= {30, b_114 + 34, &a_2};	/* WORK$7 */
static cob_field f_123	= {53, b_123, &a_7};	/* SS-MENU */
static cob_field f_130	= {1, b_123 + 52, &a_2};	/* WORK$14 */
static cob_field f_131	= {113, b_131, &a_7};	/* SS-TELA-REGISTRO */
static cob_field f_132	= {17, b_131, &a_7};	/* SS-CHAVE */
static cob_field f_134	= {9, b_131 + 8, &a_6};	/* WORK$16 */
static cob_field f_135	= {96, b_131 + 17, &a_7};	/* SS-DADOS */
static cob_field f_137	= {40, b_131 + 25, &a_2};	/* WORK$18 */
static cob_field f_139	= {40, b_131 + 73, &a_2};	/* WORK$20 */
static cob_field f_140	= {81, b_140, &a_7};	/* SS-ERRO */
static cob_field f_142	= {80, b_140, &a_2};	/* WORK$22 */
static cob_field f_143	= {1, b_140 + 80, &a_2};	/* WORK$23 */
static cob_field f_144	= {4, b_144, &a_1};	/* COB-CRT-STATUS */

/* End of fields */

/* Constants */
static cob_field c_1	= {1, (unsigned char *)"2", &a_3};
static cob_field c_2	= {8, (unsigned char *)"ADDRESS:", &a_2};
static cob_field c_3	= {2, (unsigned char *)"12", &a_5};
static cob_field c_4	= {2, (unsigned char *)"10", &a_5};
static cob_field c_5	= {8, (unsigned char *)"NAME   :", &a_2};
static cob_field c_6	= {2, (unsigned char *)"11", &a_5};
static cob_field c_7	= {8, (unsigned char *)"PHONE  :", &a_2};
static cob_field c_8	= {2, (unsigned char *)"13", &a_5};
static cob_field c_9	= {1, (unsigned char *)"1", &a_3};
static cob_field c_10	= {8, (unsigned char *)"CHOOSE: ", &a_2};
static cob_field c_11	= {2, (unsigned char *)"15", &a_5};
static cob_field c_12	= {8, (unsigned char *)"X - EXIT", &a_2};
static cob_field c_13	= {10, (unsigned char *)"4 - DELETE", &a_2};
static cob_field c_14	= {10, (unsigned char *)"3 - MODIFY", &a_2};
static cob_field c_15	= {2, (unsigned char *)"09", &a_5};
static cob_field c_16	= {9, (unsigned char *)"2 - QUERY", &a_2};
static cob_field c_17	= {2, (unsigned char *)"08", &a_5};
static cob_field c_18	= {7, (unsigned char *)"1 - ADD", &a_2};
static cob_field c_19	= {2, (unsigned char *)"07", &a_5};
static cob_field c_20	= {2, (unsigned char *)"01", &a_5};
static cob_field c_21	= {2, (unsigned char *)"02", &a_5};
static cob_field c_22	= {12, (unsigned char *)"clientes.dat", &a_2};
static cob_field c_23	= {21, (unsigned char *)"COB_SCREEN_EXCEPTIONS", &a_2};
static cob_field c_24	= {1, (unsigned char *)"Y", &a_2};
static cob_field c_25	= {14, (unsigned char *)"COB_SCREEN_ESC", &a_2};
static cob_field c_26	= {8, (unsigned char *)"ESCDELAY", &a_2};
static cob_field c_27	= {2, (unsigned char *)"25", &a_2};
static cob_field c_28	= {4, (unsigned char *)"MENU", &a_2};
static cob_field c_29	= {31, (unsigned char *)"\106\101\126\117\122\040\111\116\106\117\122\115\101\122\040\116\101\115\105\040\105\040\105\116\104\105\122\105\303\207\117", &a_2};
static cob_field c_30	= {18, (unsigned char *)"\103\114\111\105\116\124\105\040\112\303\201\040\105\130\111\123\124\105", &a_2};
static cob_field c_31	= {15, (unsigned char *)"PRESSIONE ENTER", &a_2};
static cob_field c_32	= {14, (unsigned char *)"ERRO AO GRAVAR", &a_2};
static cob_field c_33	= {38, (unsigned char *)"\103\117\116\106\111\122\115\101\040\101\040\105\130\103\114\125\123\303\203\117\040\104\117\040\103\114\111\105\116\124\105\040\050\123\057\116\051\077", &a_2};
static cob_field c_34	= {15, (unsigned char *)"ERRO AO EXCLUIR", &a_2};
static cob_field c_35	= {23, (unsigned char *)"\103\114\111\105\116\124\105\040\116\303\203\117\040\105\116\103\117\116\124\122\101\104\117", &a_2};

