/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 22:07:16 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */

/* File FILE1 */
static struct cob_file_key	*k_FILE1 = NULL;
static cob_file		*h_FILE1 = NULL;
static unsigned char	h_FILE1_status[4];

/* Screens */

static cob_screen s_143 = {NULL, NULL, &f_143, NULL, NULL, &c_1, &f_30, &f_29, 1, 0, 2625540};
static cob_screen s_142 = {&s_143, NULL, &f_142, NULL, &f_27, &c_1, &f_30, &f_29, 1, 0, 4128};
static cob_screen s_141 = {NULL, &s_142, NULL, NULL, NULL, NULL, &f_30, &f_29, 0, 0, 4096};
static cob_screen s_140 = {NULL, &s_141, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_139 = {NULL, NULL, &f_139, NULL, NULL, &c_1, NULL, NULL, 1, 0, 2621444};
static cob_screen s_138 = {&s_139, NULL, NULL, &c_2, &c_3, &c_4, NULL, NULL, 2, 0, 0};
static cob_screen s_137 = {&s_138, NULL, &f_137, NULL, NULL, &c_1, NULL, NULL, 1, 0, 2621444};
static cob_screen s_136 = {&s_137, NULL, NULL, &c_5, &c_6, &c_4, NULL, NULL, 2, 0, 0};
static cob_screen s_135 = {NULL, &s_136, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_134 = {NULL, NULL, &f_134, NULL, NULL, &c_1, &f_30, NULL, 1, 0, 2621444};
static cob_screen s_133 = {&s_134, NULL, NULL, &c_7, &c_4, &c_4, &f_30, NULL, 2, 0, 0};
static cob_screen s_132 = {&s_135, &s_133, NULL, NULL, NULL, NULL, &f_30, NULL, 0, 0, 0};
static cob_screen s_131 = {&s_140, &s_132, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_130 = {NULL, NULL, &f_130, NULL, &c_8, &c_9, &f_30, NULL, 1, 0, 2621460};
static cob_screen s_129 = {&s_130, NULL, NULL, &c_10, &c_8, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_128 = {&s_129, NULL, NULL, &c_12, &c_6, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_127 = {&s_128, NULL, NULL, &c_13, &c_4, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_126 = {&s_127, NULL, NULL, &c_14, &c_15, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_125 = {&s_126, NULL, NULL, &c_16, &c_17, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_124 = {&s_125, NULL, NULL, &c_18, &c_19, &c_11, &f_30, NULL, 2, 0, 0};
static cob_screen s_123 = {&s_131, &s_124, NULL, NULL, NULL, NULL, &f_30, NULL, 0, 0, 0};
static cob_screen s_122 = {NULL, NULL, &f_122, NULL, &f_27, &c_1, &f_30, &f_29, 1, 0, 4608};
static cob_screen s_121 = {NULL, &s_122, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_120 = {NULL, NULL, &f_120, NULL, &c_20, &c_21, &f_30, &f_29, 1, 0, 4096};
static cob_screen s_119 = {&s_121, &s_120, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_118 = {NULL, NULL, &f_118, NULL, &f_27, &c_20, NULL, &f_29, 1, 0, 512};
static cob_screen s_117 = {&s_118, NULL, &f_117, NULL, &c_20, &c_20, NULL, &f_29, 1, 0, 512};
static cob_screen s_116 = {&s_117, NULL, &f_116, NULL, NULL, NULL, NULL, NULL, 1, 0, 128};
static cob_screen s_115 = {&s_119, &s_116, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_114 = {&s_123, &s_115, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

