/**
* Example
* Example REST Endpoint.
*
* OpenAPI spec version: 2.3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "pistache/endpoint.h"
#include "pistache/http.h"
#include "pistache/router.h"
#include "DefaultApiImpl.h"

using namespace io::swagger::server::api;

int main() {
    Pistache::Address addr(Pistache::Ipv4::any(), Pistache::Port(8080));

    DefaultApiImpl server(addr);
    server.init(2);
    server.start();

    server.shutdown();
}

