#!/bin/bash
[ -z "$1" ] && echo "Usage $0 [file.kml]" && exit
echo $(cat $1|\
	/bin/grep "<description>\|<coordinates>"|\
	sed -r 's#.*>(.*)</.*#\1:#g;s/&lt;br&gt;//g'|\
	sed -r "s/^([0-9.]*),([0-9.]*):$/\2, \1>/g")|\
	sed "s/> /\n/g"|\
	sed "s/>//g"|\
	sed -r 's/^(.*): (.*)$/\2:\1/g'
