#!/bin/bash

[ -z "$1" ] && { echo "Syntax: ccc FILENAME"; exit; }

CFILE=${1%.*}
[ ! -e $CFILE.cpp ] && {
	cp ~/bin/helloworld.cpp $CFILE.cpp
	cp ~/bin/helloworld.cpp.x   .x
	cp ~/bin/helloworld.cpp.k   .k
	sed "s/helloworld/$CFILE/g" ~/bin/helloworld.cpp.cmakelists > CMakeLists.txt
}
