/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 21:32:53 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : screendemo */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_13[54] __attribute__((aligned));	/* test-record */
static unsigned char b_18[35] __attribute__((aligned));	/* a-message */
static unsigned char b_19[1] __attribute__((aligned));	/* field-1-color */
static unsigned char b_20[1] __attribute__((aligned));	/* hek */
static unsigned char b_21[1] __attribute__((aligned));	/* blank-screen */
static unsigned char b_23[195] __attribute__((aligned));	/* entry-screen */
static unsigned char b_34[89] __attribute__((aligned));	/* exit-screen */
static unsigned char b_44[4] __attribute__((aligned));	/* COB-CRT-STATUS */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {16, 4, 0, 0, NULL};
static const cob_field_attr a_2 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_3 = {16, 2, 0, 0, NULL};
static const cob_field_attr a_4 = {16, 1, 0, 0, NULL};
static const cob_field_attr a_5 = {1, 0, 0, 0, NULL};

/* Fields */

/* PROGRAM-ID : screendemo */
static cob_field f_14	= {10, b_13, &a_2};	/* last-name */
static cob_field f_15	= {10, b_13 + 10, &a_2};	/* first-name */
static cob_field f_16	= {9, b_13 + 20, &a_2};	/* soc-sec-no */
static cob_field f_17	= {25, b_13 + 29, &a_2};	/* comment */
static cob_field f_18	= {35, b_18, &a_2};	/* a-message */
static cob_field f_20	= {1, b_20, &a_2};	/* hek */
static cob_field f_21	= {1, b_21, &a_5};	/* blank-screen */
static cob_field f_22	= {1, b_21, &a_2};	/* WORK$1 */
static cob_field f_23	= {195, b_23, &a_5};	/* entry-screen */
static cob_field f_24	= {1, b_23, &a_2};	/* WORK$2 */
static cob_field f_26	= {10, b_23 + 16, &a_2};	/* screen-last-name */
static cob_field f_28	= {10, b_23 + 42, &a_2};	/* screen-first-name */
static cob_field f_30	= {9, b_23 + 68, &a_2};	/* screen-soc-sec-no */
static cob_field f_32	= {25, b_23 + 90, &a_2};	/* screen-comment */
static cob_field f_33	= {80, b_23 + 115, &a_2};	/* screen-message */
static cob_field f_34	= {89, b_34, &a_5};	/* exit-screen */
static cob_field f_35	= {1, b_34, &a_2};	/* WORK$7 */
static cob_field f_38	= {10, b_34 + 25, &a_2};	/* exit-last-name */
static cob_field f_39	= {10, b_34 + 35, &a_2};	/* exit-first-name */
static cob_field f_40	= {9, b_34 + 45, &a_2};	/* exit-soc */
static cob_field f_41	= {25, b_34 + 54, &a_2};	/* exit-comment */
static cob_field f_43	= {1, b_34 + 88, &a_2};	/* exit-hek */
static cob_field f_44	= {4, b_44, &a_1};	/* COB-CRT-STATUS */

/* End of fields */

/* Constants */
static cob_field c_1	= {2, (unsigned char *)"24", &a_3};
static cob_field c_2	= {2, (unsigned char *)"40", &a_3};
static cob_field c_3	= {9, (unsigned char *)"hit enter", &a_2};
static cob_field c_4	= {1, (unsigned char *)"1", &a_4};
static cob_field c_5	= {1, (unsigned char *)"7", &a_4};
static cob_field c_6	= {2, (unsigned char *)"18", &a_3};
static cob_field c_7	= {1, (unsigned char *)"6", &a_4};
static cob_field c_8	= {1, (unsigned char *)"5", &a_4};
static cob_field c_9	= {1, (unsigned char *)"4", &a_4};
static cob_field c_10	= {12, (unsigned char *)"  Last name:", &a_2};
static cob_field c_11	= {12, (unsigned char *)"You entered:", &a_2};
static cob_field c_12	= {1, (unsigned char *)"2", &a_4};
static cob_field c_13	= {2, (unsigned char *)"10", &a_3};
static cob_field c_14	= {1, (unsigned char *)"8", &a_4};
static cob_field c_15	= {13, (unsigned char *)"Enter Comment", &a_2};
static cob_field c_16	= {16, (unsigned char *)"Enter Social Sec", &a_2};
static cob_field c_17	= {16, (unsigned char *)"Enter First Name", &a_2};
static cob_field c_18	= {1, (unsigned char *)"3", &a_4};
static cob_field c_19	= {15, (unsigned char *)"Enter Last Name", &a_2};

