/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 21:32:53 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */


/* Screens */

static cob_screen s_43 = {NULL, NULL, &f_43, NULL, &c_1, &c_2, NULL, NULL, 1, 0, 2621440};
static cob_screen s_42 = {&s_43, NULL, NULL, &c_3, &c_1, &c_4, NULL, NULL, 2, 0, 0};
static cob_screen s_41 = {&s_42, NULL, &f_41, NULL, &c_5, &c_6, NULL, NULL, 1, 0, 0};
static cob_screen s_40 = {&s_41, NULL, &f_40, NULL, &c_7, &c_6, NULL, NULL, 1, 0, 0};
static cob_screen s_39 = {&s_40, NULL, &f_39, NULL, &c_8, &c_6, NULL, NULL, 1, 0, 0};
static cob_screen s_38 = {&s_39, NULL, &f_38, NULL, &c_9, &c_6, NULL, NULL, 1, 0, 0};
static cob_screen s_37 = {&s_38, NULL, NULL, &c_10, &c_9, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_36 = {&s_37, NULL, NULL, &c_11, &c_12, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_35 = {&s_36, NULL, &f_35, NULL, &c_4, NULL, NULL, NULL, 1, 0, 128};
static cob_screen s_34 = {NULL, &s_35, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_33 = {NULL, NULL, &f_33, NULL, &c_13, &c_8, NULL, NULL, 1, 0, 0};
static cob_screen s_32 = {&s_33, NULL, &f_32, NULL, &c_14, &c_8, NULL, NULL, 1, 0, 2621440};
static cob_screen s_31 = {&s_32, NULL, NULL, &c_15, &c_5, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_30 = {&s_31, NULL, &f_30, NULL, &c_7, &c_8, NULL, NULL, 1, 0, 2719744};
static cob_screen s_29 = {&s_30, NULL, NULL, &c_16, &c_8, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_28 = {&s_29, NULL, &f_28, NULL, &c_9, &c_8, NULL, NULL, 1, 0, 2621440};
static cob_screen s_27 = {&s_28, NULL, NULL, &c_17, &c_18, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_26 = {&s_27, NULL, &f_26, NULL, &c_12, &c_8, NULL, NULL, 1, 0, 2621440};
static cob_screen s_25 = {&s_26, NULL, NULL, &c_19, &c_4, &c_8, NULL, NULL, 2, 0, 0};
static cob_screen s_24 = {&s_25, NULL, &f_24, NULL, NULL, NULL, NULL, NULL, 1, 0, 128};
static cob_screen s_23 = {&s_34, &s_24, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};
static cob_screen s_22 = {NULL, NULL, &f_22, NULL, &c_4, NULL, NULL, NULL, 1, 0, 128};
static cob_screen s_21 = {&s_23, &s_22, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0};


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

