/* Generated by            cobc 1.1.0 */
/* Generated from          app.cob */
/* Generated at            Jan 14 2018 21:32:53 CET */
/* OpenCOBOL build date    Mar 01 2014 13:11:28 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C app.cob */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"app.cob"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "app.c.h"

/* Function prototypes */

int screendemo (void);
static int screendemo_ (const int);

/* Functions */

int
screendemo ()
{
  return screendemo_ (0);
}

static int
screendemo_ (const int entry)
{
  /* Local variables */
  #include "app.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, &f_44, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      if (module.next)
        cob_set_cancel ((const char *)"screendemo", (void *)screendemo, (void *)screendemo_);
      (*(int *) (b_1)) = 0;
      memset (b_13, 32, 54);
      memset (b_18, 32, 35);
      *(unsigned char *)(b_19) = 48;
      *(unsigned char *)(b_20) = 32;
      memset (b_44, 48, 4);
      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry screendemo */

  l_2:;

  /* MAIN SECTION */

  /* MAIN PARAGRAPH */

  /* app.cob:74: DISPLAY */
  {
    cob_screen_display (&s_21, NULL, NULL);
  }

  /* screen-loop */

  l_5:;
  /* app.cob:77: DISPLAY */
  {
    cob_move (&f_18, &f_33);
    cob_move (&f_17, &f_32);
    cob_move (&f_16, &f_30);
    cob_move (&f_15, &f_28);
    cob_move (&f_14, &f_26);
    cob_screen_display (&s_23, NULL, NULL);
  }
  /* app.cob:78: ACCEPT */
  {
    cob_move (&f_18, &f_33);
    cob_move (&f_17, &f_32);
    cob_move (&f_16, &f_30);
    cob_move (&f_15, &f_28);
    cob_move (&f_14, &f_26);
    cob_screen_accept (&s_23, NULL, NULL);
    cob_move (&f_32, &f_17);
    cob_move (&f_30, &f_16);
    cob_move (&f_28, &f_15);
    cob_move (&f_26, &f_14);
  }
  /* app.cob:79: IF */
  {
    if (((int)(int)(*(b_13 + 0) - 113) != 0))
      {
        /* app.cob:80: MOVE */
        {
          *(b_19) = 50;
        }
        /* app.cob:81: MOVE */
        {
          memcpy (b_18, "Last name must begin with q to exit", 35);
        }
        /* app.cob:82: DISPLAY */
        {
          cob_move (&f_18, &f_33);
          cob_move (&f_17, &f_32);
          cob_move (&f_16, &f_30);
          cob_move (&f_15, &f_28);
          cob_move (&f_14, &f_26);
          cob_screen_display (&s_23, NULL, NULL);
        }
        /* app.cob:83: GO TO */
        {
          goto l_5;
        }
      }
  }
  /* app.cob:86: DISPLAY */
  {
    cob_move (&f_20, &f_43);
    cob_move (&f_17, &f_41);
    cob_move (&f_16, &f_40);
    cob_move (&f_15, &f_39);
    cob_move (&f_14, &f_38);
    cob_screen_display (&s_34, NULL, NULL);
  }
  /* app.cob:87: ACCEPT */
  {
    cob_move (&f_20, &f_43);
    cob_move (&f_17, &f_41);
    cob_move (&f_16, &f_40);
    cob_move (&f_15, &f_39);
    cob_move (&f_14, &f_38);
    cob_screen_accept (&s_34, NULL, NULL);
    cob_move (&f_43, &f_20);
  }
  /* app.cob:89: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));
}

/* End functions */

