/**
* Example
* Example REST Endpoint.
*
* OpenAPI spec version: 2.3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* DefaultApiImpl.h
*
* 
*/

#ifndef DEFAULT_API_IMPL_H_
#define DEFAULT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <DefaultApi.h>

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace api {

//using namespace io::swagger::server::model;

class DefaultApiImpl : public io::swagger::server::api::DefaultApi {
public:
    DefaultApiImpl(Pistache::Address addr);
    ~DefaultApiImpl() { };

    void parameter1_get(const std::string &parameter1, Pistache::Http::ResponseWriter &response);
    void parameter1_parameter2_get(const std::string &parameter1, const std::string &parameter2, Pistache::Http::ResponseWriter &response);
    void parameter1_parameter2_parameter3_get(const std::string &parameter1, const std::string &parameter2, const std::string &parameter3, Pistache::Http::ResponseWriter &response);
    void parameter1_parameter2_parameter3_parameter4_get(const std::string &parameter1, const std::string &parameter2, const std::string &parameter3, const std::string &parameter4, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif
