#!/bin/bash

echo Setting up container...
[ ! -d /app/src ] && [ -d /usr/app/src ] && {
	echo "Application wasn't found. Creating application from template..."
	cp -r /usr/src/* /usr/src/.[a-z]* /app/
	echo Done.
}
[ ! -d /app/src ] && {
	echo "Application wasn't found. Creating application with yarn..."
	cd /app
	create-react-app .
	yarn add react-admin ra-data-json-server prop-types
	echo Done.
}
echo "Application found. Starting up yarn..."
cd /app
yarn start
